  title: webR in Quarto HTML Documents
  format: html
  engine: knitr
  resources:
  - webr-serviceworker.js
  - webr-worker.js
  filters:
    - webr
  date: "7/12/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd




