project:
  type: book
  output-dir: docs

book:
  title: "Applied Psychometrics Using R"
  author: "authors"
  date: "date"
  
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - Using R.qmd
        - Types of Assessments.qmd
    - part: Content Domain Population.qmd
      chapters:
        - Nomological Networks.qmd
        - Item Sampling.qmd
        - Scale Development.qmd
    - part: Data Collection.qmd
      chapters:
        - Population & Sampling.qmd
    - part: Psychometric Philosophies.qmd
      chapters:
        - Reflective vs. Formative Measurement.qmd
        - Internal Empirical Associations.qmd
        - External Empirical Associations.qmd
        - Legal Considerations & Additional Analyses.qmd
    - part: Documentation & Guides.qmd
      chapters: 
        - techreport.qmd
    - part: Practical Guides.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: lux
  epub:
    cover-image: cover.png

engine: knitr

webr:
  show-starup-message: false
  packages: ['ggplot2','dplyr']

filters:
  - webr