project:
  type: book
  output-dir: docs

book:
  title: "Applied Psychometrics Using R"
  author: "authors"
  date: "date"
  navbar:
    right:
      - href: "https://github.com/johnsonemilyj/psychometric-book/issues"
        text: "Report Issues" 
        icon: github
  chapters:
    - index.qmd
    - part: intro.qmd
      chapters:
        - Using R.qmd
        - Psychometric Philosophies.qmd
        - Types of Assessments.qmd
    - part: Scale Development.qmd
      chapters:
        - Nomological Networks.qmd
        - Domain Sampling.qmd
    - part: Scale Evaluation.qmd
      chapters:
        - Internal Empirical Associations.qmd
        - External Empirical Associations.qmd
    - part: Population and Sampling.qmd
      chapters:
        - Convenience Sampling.qmd
    - part: Documentation & Guides.qmd
      chapters: 
        - techreport.qmd
        - Legal Considerations & Additional Analyses.qmd
    - part: Appendix
      chapters:
        - summary.qmd
        - references.qmd
        - glossary.qmd

bibliography: [references.bib,ej.bib,kulas.bib]
csl: apa7.csl

format:
  html:
    theme: [lux, custom.css]
    glossary:             # debruine/quarto-glossary
      path: glossary.yml  # Path to your definitions file
      popup: hover        # Or 'click'/'none'
      show: true          # Include terms in the table
  epub:
    cover-image: cover.png

engine: knitr

lightbox: true

webr:
  show-starup-message: false
  packages: ['psych','tidyverse']

filters:
  - webr