# Introduction

## Organizing Principles

The structure of this book parallels ***project sequence***. The more traditional presentation of Psychometrics is organized by fundamental concepts. This was a deliberate choice and intended to better serve the ***developer of psychological assessments***. 

The content is informed by the current literature on Psychological measurement [e.g., @borsboom2022possible] as well as important foundational sources [e.g., @stevens1946theory] and one guiding "North Star", the Standards for Educational and Psychological Testing [@aera_apa_ncme_2014]. We have made every effort to, where appropriate, link the current book material to corresponding Standards within the forthcoming edition (edition 8).

By tradition, the ***development*** of a measure is aligned with one predominant philosophical orientation, although analytical explorations are often conducted via the application of multiple orientations. This is smart, as multiple investigations from multiple angles should provide the most information regarding the effectiveness of a measure. We have tried to be careful about our use of the words "tradition" and "philosophy" such that "tradition" is a categorical label whereas "philosophy" connotes more meaningful differences in thought or specification regarding the nature of measurement.

Consistent with this, "diversity of traditions is good" perspective^[sorry Raschies!!!], we take an atypical route toward presentation and integration of different psychometric traditions -- we separate psychometric traditions (classical test theory, item response theory, network psychometrics) from the ***procedures*** often tied to those traditions. 

This will likely be the most controversial structural decision we have made, although it is again aligned with the needs of the practitioner (test developer and analyst), who should be provided multiple options (aka *procedures*) for any one investigation (aka *analysis*). The consequential, philosophical orientations of each tradition is handled separately, in @sec-psychophilosophies. 

```{r}

Philosophy <- c("CTT", "IRT", "Rasch")
Analysis <- c("item difficulty", "item difficulty", "item difficulty")
Procedure <- c("item average", "1PL estimation", "logodds")

temp <- as.data.frame(cbind(Philosophy, Analysis, Procedure))

kableExtra::kable(temp)

```

We view Psychometrics as an application of Psychological methods and analyses to the domain of measurement. Our presentation, therefore, is informed by traditions and advancements within methodology and statistics.

Why/how is this different:

1. Organized based on project sequence
2. Elements tied to standards 
3. WebR for interactivity right there
4. Graphics for different components**
5. Tests versus inventories and their suceptibility to different forms of response bias

>NOTE. Come back and fill this in after final outline is complete and decision is made on how to incorporate `WebR` -- within main resource or as an "external" supplement (instead using `echo: true` code blocks throughout this presentation)

The structure of the book...

To get the most out of this book...

All applications are interactive and intended to be executed within the reader's browser -- alternatively the code can also be "copied" and "pasted" into the reader's local R session, if that is preferred. 


